# version é obsoleto, aparentemente
# version: "3.8"

services: # Define os containers
    db:
        image: postgres
        container_name: api_receitas_postgres
        restart: always
        # Set shared mem limit when using compose
        shm_size: 128mb
        environment:
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_USER: ${POSTGRES_USER}
        volumes: # Para persistência do DB (após o container ser 'fechado')
            - pgdata:/var/lib/postgresql/data
        networks:
            - apinet

    migrator: # Para rodar as migrations antes de subir o container do API
        build:
            context: .
            target: build
        container_name: api_migrator
        environment:
            - ASPNETCORE_ENVIRONMENT=Production
            - ConnectionStrings__Default=${CONNECTION_STRING}
        depends_on:
            - db
        networks:
            - apinet
        entrypoint: ["sh", "-c", "dotnet ef database update"]

    api:
        build: .
        container_name: api_backend
        environment:
            - ASPNETCORE_ENVIRONMENT=Production
            - ConnectionStrings__Default=${CONNECTION_STRING}
        depends_on:
            - db
        networks:
            - apinet
        ports:
            - 8080:8080

volumes:
    pgdata:

networks:
    apinet:
