// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using api_receitas.Data;

#nullable disable

namespace api_receitas.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.15");

            modelBuilder.Entity("IngredienteModelReceitaModel", b =>
                {
                    b.Property<Guid>("IngredientesId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ReceitasId")
                        .HasColumnType("TEXT");

                    b.HasKey("IngredientesId", "ReceitasId");

                    b.HasIndex("ReceitasId");

                    b.ToTable("IngredienteModelReceitaModel");
                });

            modelBuilder.Entity("api_receitas.Models.IngredienteModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAtivo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.Property<string>("Unidade")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Ingrediente");
                });

            modelBuilder.Entity("api_receitas.Models.ReceitaIngredienteModel", b =>
                {
                    b.Property<Guid>("ReceitaId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("IngredienteId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Quantidade")
                        .HasColumnType("TEXT");

                    b.HasKey("ReceitaId", "IngredienteId");

                    b.HasIndex("IngredienteId");

                    b.ToTable("ReceitaIngrediente");
                });

            modelBuilder.Entity("api_receitas.Models.ReceitaModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAtivo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ModoPreparo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.Property<int>("Porcoes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TempoPreparo")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Receita");
                });

            modelBuilder.Entity("IngredienteModelReceitaModel", b =>
                {
                    b.HasOne("api_receitas.Models.IngredienteModel", null)
                        .WithMany()
                        .HasForeignKey("IngredientesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("api_receitas.Models.ReceitaModel", null)
                        .WithMany()
                        .HasForeignKey("ReceitasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("api_receitas.Models.ReceitaIngredienteModel", b =>
                {
                    b.HasOne("api_receitas.Models.IngredienteModel", "Ingrediente")
                        .WithMany("ReceitaIngredientes")
                        .HasForeignKey("IngredienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("api_receitas.Models.ReceitaModel", "Receita")
                        .WithMany("ReceitaIngredientes")
                        .HasForeignKey("ReceitaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingrediente");

                    b.Navigation("Receita");
                });

            modelBuilder.Entity("api_receitas.Models.IngredienteModel", b =>
                {
                    b.Navigation("ReceitaIngredientes");
                });

            modelBuilder.Entity("api_receitas.Models.ReceitaModel", b =>
                {
                    b.Navigation("ReceitaIngredientes");
                });
#pragma warning restore 612, 618
        }
    }
}
